apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: ecom
  labels: { app: checkout-service }
spec:
  replicas: 1
  selector:
    matchLabels: { app: checkout-service }
  template:
    metadata:
      labels: { app: checkout-service }
    spec:
      nodeSelector:
        cloud.google.com/compute-class: ecom-spot
      tolerations:
        - key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
          effect: NoSchedule
      terminationGracePeriodSeconds: 25
      containers:
        - name: checkout
          image: us-central1-docker.pkg.dev/terraform-project-883456/ecom-microservices/checkout-service:f7d8804
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: CART_SERVICE_URL
              value: "http://cart-service:8082"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:8084"
          resources:
            requests: { cpu: 50m, memory: 96Mi }
            limits:   { cpu: 250m, memory: 192Mi }
          readinessProbe:
            httpGet: { path: /health, port: 8083 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8083 }
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: ecom
spec:
  selector: { app: checkout-service }
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkout-service
  namespace: ecom
spec:
  maxUnavailable: 1
  selector:
    matchLabels: { app: checkout-service }
