# =============================================================================
# Destroy-time grace window for ArgoCD's cascade-delete to drain.
#
# When the Application CR is deleted, the resources-finalizer triggers
# ArgoCD to remove every tracked k8s resource — including the Gateway
# and HTTPRoutes. The GKE Gateway controller (in the cluster's control
# plane) then asynchronously deletes the global LB, target proxies,
# url maps, and forwarding rules. That tear-down takes ~30-60 seconds.
#
# Without this sleep, terraform proceeds straight from "Application CR
# gone" to "cluster destroyed" — and any LB resources the controller
# hadn't finished freeing become orphans. They then block the
# CertificateMap delete with "can't delete certificate map that is
# referenced by a target proxy".
#
# 90s is enough for routine deploys; bump it if your Gateway count
# grows.
# =============================================================================
resource "time_sleep" "argocd_cascade_grace" {
  depends_on       = [helm_release.argocd]
  destroy_duration = "90s"
}

# =============================================================================
# Wire ArgoCD to the private GitHub repo via a read-only SSH deploy key.
#
# The deploy key was generated by `ssh-keygen` outside terraform and registered
# on the repo via `gh repo deploy-key add`. The private key file lives at
# ${path.module}/.argocd-deploy-key, gitignored.
#
# We:
#   1. Stuff that private key + the SSH repo URL into a K8s Secret with the
#      magic label argocd.argoproj.io/secret-type=repository — ArgoCD's
#      controller picks it up automatically and uses it for that repo.
#   2. Create an Application CR pointing at the repo, with auto-sync + auto-
#      prune + self-heal enabled (full GitOps).
#
# generated-config.yaml (terraform-managed ConfigMaps/SA/SPC) is NOT in git,
# so ArgoCD never sees it and won't try to manage it.
# =============================================================================

resource "kubernetes_secret_v1" "gitops_repo_creds" {
  metadata {
    name      = "ecom-gitops-repo"
    namespace = kubernetes_namespace.argocd.metadata[0].name
    labels = {
      "argocd.argoproj.io/secret-type" = "repository"
    }
  }
  type = "Opaque"
  data = {
    type          = "git"
    url           = var.gitops_repo_ssh_url
    sshPrivateKey = file("${path.module}/.argocd-deploy-key")
  }

  depends_on = [helm_release.argocd]
}

resource "kubernetes_manifest" "ecom_application" {
  # ArgoCD's own controller writes status + some spec fields. Use SSA with
  # force_conflicts so terraform takes ownership of the fields it sets and
  # ignores what the controller manages.
  field_manager {
    force_conflicts = true
  }

  manifest = {
    apiVersion = "argoproj.io/v1alpha1"
    kind       = "Application"
    metadata = {
      name      = "ecom"
      namespace = kubernetes_namespace.argocd.metadata[0].name
      # Ensures the Application's tracked resources are cascade-deleted when
      # the Application itself is removed.
      finalizers = ["resources-finalizer.argocd.argoproj.io"]
    }
    spec = {
      project = "default"

      source = {
        repoURL        = var.gitops_repo_ssh_url
        targetRevision = var.gitops_repo_branch
        path           = var.gitops_repo_path
        directory = {
          recurse = false
        }
      }

      destination = {
        server    = "https://kubernetes.default.svc"
        namespace = var.gitops_app_namespace
      }

      # Annotations + status fields added/normalized by controllers must be
      # ignored or ArgoCD will permanently flap trying to overwrite them while
      # the controller re-applies them.
      ignoreDifferences = [
        {
          group = ""
          kind  = "Service"
          jqPathExpressions = [
            # Written by the NEG controller — not in git.
            ".metadata.annotations.\"cloud.google.com/neg-status\"",
            # Authored in git but GKE re-serializes the JSON value to compact
            # form (no spaces). ArgoCD diffs the string, so any whitespace
            # difference in git causes permanent OutOfSync flap. Letting GKE
            # own the serialized form sidesteps the trap regardless of how
            # the YAML is formatted.
            ".metadata.annotations.\"cloud.google.com/neg\"",
          ]
        },
        {
          # Replicas are managed by HPA, not git. Without this, every HPA
          # scale event would mark the Deployment OutOfSync.
          group = "apps"
          kind  = "Deployment"
          jsonPointers = ["/spec/replicas"]
        },
      ]

      syncPolicy = {
        # Full GitOps: any drift from git auto-corrects.
        automated = {
          prune      = true # delete resources removed from git
          selfHeal   = true # revert manual kubectl edits back to git state
          allowEmpty = false
        }
        syncOptions = [
          "CreateNamespace=true",       # ArgoCD creates the ecom ns if missing
          "PrunePropagationPolicy=foreground",
          "PruneLast=true",             # delete leaf resources first
          # ApplyOutOfSyncOnly removed: its diff cache went stale on a v2->v1
          # image bump, causing ArgoCD to report Synced without re-applying
          # Deployments. The few extra seconds per sync are worth the
          # correctness guarantee.
          "ServerSideApply=true",       # avoids diffs against the legacy
                                        # kubectl.kubernetes.io/last-applied-configuration
                                        # annotation on pre-ArgoCD resources
        ]
        retry = {
          limit = 5
          backoff = {
            duration    = "5s"
            factor      = 2
            maxDuration = "3m"
          }
        }
      }
    }
  }

  # Routed through time_sleep.argocd_cascade_grace (instead of straight to
  # helm_release.argocd) so the destroy order is:
  #   1) kubernetes_manifest.ecom_application deleted (ArgoCD cascade-deletes
  #      Gateway/HTTPRoute and the GKE controller starts freeing the LB)
  #   2) time_sleep.argocd_cascade_grace destroys (sleeps 90s — gives the
  #      controller time to finish)
  #   3) helm_release.argocd deleted
  #   4) cluster deleted (LB already cleaned up — CertMap delete works)
  depends_on = [
    time_sleep.argocd_cascade_grace,
    kubernetes_secret_v1.gitops_repo_creds,
  ]
}
