# =============================================================================
# GCP Secret Manager + Workload Identity for the DB password.
#
# Flow at runtime:
#   1. Pod runs as the K8s ServiceAccount `ecom-workload`
#   2. WI binding maps that K8s SA → google_service_account.workload
#   3. That GCP SA has roles/secretmanager.secretAccessor on the password secret
#   4. The SecretManager CSI driver (installed by the GKE add-on) fetches the
#      secret and syncs it into a K8s Secret via the SecretProviderClass
#   5. Deployments inject the password via standard secretKeyRef env vars
# =============================================================================

# The need-to-know secret: the DB password generated by random_password.
resource "google_secret_manager_secret" "db_password" {
  secret_id = var.gsm_db_password_secret_name

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "db_password_v1" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db_password.result
}

# Dedicated service account for app workloads. Distinct from the GKE node SA
# (which only needs registry/logging permissions) so we can scope app-level
# secret access narrowly.
resource "google_service_account" "workload" {
  account_id   = var.workload_sa_id
  display_name = "Ecom workload SA (for Workload Identity → Secret Manager)"
}

# Grant the workload SA read access on the password secret only.
resource "google_secret_manager_secret_iam_member" "workload_can_read_password" {
  secret_id = google_secret_manager_secret.db_password.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.workload.email}"
}

# Workload Identity binding: allow the K8s ServiceAccount `ecom-workload` in
# the `ecom` namespace to impersonate the GCP service account.
resource "google_service_account_iam_member" "wi_binding" {
  service_account_id = google_service_account.workload.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:${var.project_id}.svc.id.goog[ecom/${var.k8s_workload_sa_name}]"
}
